// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcgwtmgvdasnlrmbpvko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZ3d0bWd2ZGFzbmxybWJwdmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzNDY5MzksImV4cCI6MjA0NzkyMjkzOX0.YXaJXkxVMCsXNZS1a0xSSrfvriDsLIz3JyxhioKYilg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);